theme = "plain"
icons = "awesome"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = true
speed_up = false
speed_down = false
interval = 10

[[block]]
block = "battery"
show = "percentage"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m %R"
